### PR TITLE
completed step 5

### PR DESCRIPTION
**Pull request by noliver-ykc**
## What
Built docker file and connected to listing API

Im still rather unfamiliar with docker so please let me know if i did anything wrong!
Heres a screen shot of my commands
[dockerOutput.pdf](https://github.com/noliver-ykc/mercari-build-training-2023/files/11499218/dockerOutput.pdf)

## CHECKS :warning:

Please make sure you are aware of the following.

- [x] **The changes in this PR doesn't have private information

### CODE REVIEW

**Comment by karuna** [comment]
what is the `python/getting-started` submodule?

**Comment by noliver-ykc** [comment]
> what is the `python/getting-started` submodule?

im not really sure? it seemed to of just magically appeared-- although i know thats not a great answer.

**Comment by karuna** [comment]
Did you accidentally add git submodule? https://www.atlassian.com/git/tutorials/git-submodule
If you don't need the folder, maybe try removing the submodule.

**Review by iggyray — APPROVED** [review]
besides the submodule, lgtm!

**Comment by noliver-ykc** [comment]
> Did you accidentally add git submodule? https://www.atlassian.com/git/tutorials/git-submodule If you don't need the folder, maybe try removing the submodule.

I probably did! Ill try removing it~

**Pull request merged**
